#!/usr/bin/env ruby

ROOT = File.expand_path('.')
TEMP = File.join(ROOT, 'temp')
DEPLOY = File.join(ROOT, 'bakery')
WIDGETS = File.join(ROOT, "widgets")
SKINS = File.join(ROOT, "skins")
ENGINE = File.join(ROOT, "engine")
EDITOR = File.join(ROOT, "editor")
SYSTEM = File.join(ROOT, "system")
REDBUG = File.join(ROOT, "redbug")
FRONT = File.join(ROOT, "front")

OSX = PLATFORM =~ /darwin/
WIN = PLATFORM =~ /win32/
NIX = !(OSX || WIN)

require "rubygems"

begin
  require 'pbdev'
rescue LoadError
  begin
    $: << "/Users/darwin/code/pbdev/lib"
    require 'pbdev'
  rescue LoadError
    raise 'Please install pbdev: sudo gem install hashpage-pbdev --source http://gems.github.com'
  end
end
include PBDev

# http://kpumuk.info/ruby-on-rails/colorizing-console-ruby-script-output/
begin
  require 'Win32/Console/ANSI' if WIN
rescue LoadError
  raise 'You must "sudo gem install win32console" to use terminal colors on Windows'
end

def colorize(text, color_code)
  "#{color_code}#{text}\e[0m"
end

def red(text); colorize(text, "\e[31m"); end
def green(text); colorize(text, "\e[32m"); end
def yellow(text); colorize(text, "\e[33m"); end
def blue(text); colorize(text, "\e[34m"); end
def magenta(text); colorize(text, "\e[35m"); end
def azure(text); colorize(text, "\e[36m"); end
def white(text); colorize(text, "\e[37m"); end
def black(text); colorize(text, "\e[30m"); end

def file_color(text); yellow(text); end
def dir_color(text); blue(text); end
def cmd_color(text); azure(text); end

#############################################################################

def sanitize_path(path)
  path = path.gsub('/', '\\') if WIN
  path = path.gsub('sudo ', '') if WIN
  path
end

def system(path, *params)
  path = sanitize_path(path)
  puts yellow(">> #{path} #{params.join(' ')}")
  Kernel.system(path, *params)
end

def sys(cmd, verbose = true)
  puts yellow("> #{cmd}") if verbose
  `#{sanitize_path(cmd)}`
end

def die(s)
  puts red(s)
  exit(1)
end

def relativize_path(path)
  return path unless path[0..ROOT.size-1] == ROOT
  path[ROOT.size+1..-1]
end

#############################################################################

def reset_bake_counters()
  $bake_counters = {
    :widget => {
      :authors => 0,
      :total => 0
    },
    :skin => {
      :authors => 0,
      :total => 0
    },
    :engine => {
      :total => 0
    },
    :editor => {
      :total => 0
    },
    :system => {
      :total => 0
    },
    :redbug => {
      :total => 0
    },
    :front => {
      :total => 0
    }
  }
end

def print_bake_counters()
  puts "Processed #{azure("#{$bake_counters[:skin][:total]} skins")} / #{$bake_counters[:skin][:authors]} authors"
  puts "          #{azure("#{$bake_counters[:widget][:total]} widgets")} / #{$bake_counters[:widget][:authors]} authors"
end

def bake(type, path, dest, url, mode)
  die "DEPLOY dir is too short (paranoia)" if dest.size<10
  sys("rm -rf \"#{dest}\"")
  return unless File.exists? path
  sys("pbdev bake #{type.to_s} --mode=\"#{mode}\" --url=\"#{url}\" \"#{relativize_path(path)}\" \"#{relativize_path(dest)}\" 1>&2")
  die("Baking error ...") if $?.exitstatus!=0
  $bake_counters[type][:total] += 1
end

def bake_author(type, path, dest, url, mode)
  $bake_counters[type][:authors] += 1
  Dir.glob(File.join(path, "*")) do |path|
    next unless File.directory? path
    name = File.basename(path)
    bake(type, path, File.join(dest, name), url+"/"+name, mode)
  end
end

def bake_all(type, path, dest, url, mode)
  die "DEPLOY dir is too short (paranoia)" if dest.size<10
  sys("rm -rf \"#{dest}\"")
  return unless File.exists? path
  Dir.glob(File.join(path, "*")) do |author_path|
    next unless File.directory? author_path
    name = File.basename(author_path)
    bake_author(type, author_path, File.join(dest, name), url+name, mode)
  end
end

def pull(dir)
  puts "cd " + dir_color(dir)
  Dir.chdir(dir) do
    sys("git pull 1>&2")
  end
end

def pull_all(root)
  Dir.glob(File.join(root, "**/.git")) do |dir|
    next if dir == File.join(root, ".git")
    pull(dir[0..-6])
  end
end

def push(dir)
  puts "cd " + dir_color(dir)
  Dir.chdir(dir) do
    sys("git push push 1>&2")
  end
end

def push_all(root)
  Dir.glob(File.join(root, "skins/**/.git")) do |dir|
    next if dir == File.join(root, ".git")
    push(dir[0..-6])
  end
  Dir.glob(File.join(root, "widgets/**/.git")) do |dir|
    next if dir == File.join(root, ".git")
    push(dir[0..-6])
  end
end

def commit(dir, msg)
  puts "cd " + dir_color(dir)
  Dir.chdir(dir) do
    sys("git commit -a -m \"#{msg}\" 1>&2")
  end
end

def commit_widgets(root)
  msg = ENV["msg"] || die("specify commit message (msg param)")
  Dir.glob(File.join(root, "widgets/**/.git")) do |dir|
    next if dir == File.join(root, ".git")
    commit(dir[0..-6], msg)
  end
end

def commit_skins(root)
  msg = ENV["msg"] || die("specify commit message (msg param)")
  Dir.glob(File.join(root, "skins/**/.git")) do |dir|
    next if dir == File.join(root, ".git")
    commit(dir[0..-6], msg)
  end
end

def url(mode, server, path = nil)
  path = "" unless path
  case mode
  when :production
    return "http://#{server}.hashpage.com/#{path}"
  when :simulation
    return "http://#{server}.hashpage.local/#{path}"
  when :development
    return "http://localhost:9876/#{server}/#{path}"
  end
  "unknown url mode"
end

def is_clean?
  !!sys("git status", false).match(/working directory clean/)
end

def print_dirty(root)
  Dir.glob(File.join(root, "**/.git")) do |dir|
    next if dir == File.join(root, ".git")
    dir_path = dir[0..-6]
    Dir.chdir(dir_path) do
      puts dir_color(dir_path) unless is_clean?
    end
  end
end

#############################################################################

#----------------------------------------------------------------------------
desc "start dev server"
task :start do
  sys("pbdev 1>&2")
end

#----------------------------------------------------------------------------
desc "bake production files (local)"
task :bake do
  mode = ENV["mode"] || "production"
  what = (ENV["only"] || "widgets,skins,engine,editor,system,redbug,front").split(",")
  reset_bake_counters()
  bake_all(:widget, WIDGETS, File.join(DEPLOY, "widgets"), url(mode.to_sym, "widgets"), mode) if what.include? "widgets"
  bake_all(:skin, SKINS, File.join(DEPLOY, "skins"), url(mode.to_sym, "skins"), mode) if what.include? "skins"
  bake(:engine, ENGINE, File.join(DEPLOY, "code", "hashpage", "engine"), url(mode.to_sym, "code", "engine"), mode) if what.include? "engine"
  bake(:editor, EDITOR, File.join(DEPLOY, "code", "hashpage", "editor"), url(mode.to_sym, "code", "editor"), mode) if what.include? "editor"
  bake(:system, SYSTEM, File.join(DEPLOY, "code", "hashpage", "system"), url(mode.to_sym, "code", "system"), mode) if what.include? "system"
  bake(:redbug, REDBUG, File.join(DEPLOY, "code", "hashpage", "redbug"), url(mode.to_sym, "code", "redbug"), mode) if what.include? "redbug"
  bake(:front, FRONT, File.join(DEPLOY, "code", "hashpage", "front"), url(mode.to_sym, "code", "front"), mode) if what.include? "front"
  print_bake_counters()
end

#----------------------------------------------------------------------------
desc "pull all submodules"
task :pull do
  pull_all(ROOT)
end

#----------------------------------------------------------------------------
desc "add widget into index, eats :user and :repo"
task :add_widget do
  user = ENV["user"] or die("you have to specify github user (user=defunkt)")
  repo = ENV["repo"] or die("you have to specify github user's repo name (repo=pbw-coolbar)")
  dest = repo
  dest = repo[4..-1] if repo=~/^pbw-/
  sys("git submodule add git://github.com/#{user}/#{repo}.git widgets/#{user}/#{dest}")
  Dir.chdir("widgets/#{user}/#{dest}") do
    sys("git remote add push git@github.com:#{user}/#{repo}.git")
  end
end

#----------------------------------------------------------------------------
desc "add skin into index, eats :user and :repo"
task :add_skin do
  user = ENV["user"] or die("you have to specify github user (user=defunkt)")
  repo = ENV["repo"] or die("you have to specify github user's repo name (repo=pbs-skinner)")
  dest = repo
  dest = repo[4..-1] if repo=~/^pbs-/
  sys("git submodule add git://github.com/#{user}/#{repo}.git skins/#{user}/#{dest}")
  Dir.chdir("skins/#{user}/#{dest}") do
    sys("git remote add push git@github.com:#{user}/#{repo}.git")
  end
end

#----------------------------------------------------------------------------
desc "commit widgets, eats :msg"
task :commit_widgets do
  commit_widgets(ROOT)
end

#----------------------------------------------------------------------------
desc "commit skins, eats :msg"
task :commit_skins do
  commit_skins(ROOT)
end

#----------------------------------------------------------------------------
desc "push all submodules"
task :push do
  push_all(ROOT)
end

#----------------------------------------------------------------------------
desc "print dirty submodules"
task :dirty do
  print_dirty(ROOT)
end

#----------------------------------------------------------------------------

task :default => :start
